#! /usr/bin/env ruby
require 'kafka'
require_relative 'lib/kafka_consumer'
require 'elasticsearch'

$stdout.sync = true
Logger.new(STDOUT)
LOG = Logger.new(STDOUT)
LOG.level = Logger::DEBUG

MAX_CONNECTION_ATTEMPTS = 5
CONNECTION_ATTEMPT_WAIT = 5

LOG.info "waiting to connect to kafka"
sleep 60
LOG.info "connecting to kafka"

consumer = KafkaConsumer.with_seed_brokers(['kafka:9092'])
esclient = Elasticsearch::Client.new(hosts: [{ host: 'elasticsearch', port: '9200', scheme: 'http' }], log: true)
esclient.indices.create(index: 'logstash-central_logging',
                        body: { settings: { number_of_shards: 1 },
                                mappings: { type1: { properties: { api_version: { type: "keyword" },
                                                                   timestamp:   { type: "date" } } } } }) rescue nil

# '66.249.65.159 - - [2017-03-17:21:13:10] "GET /api/2016-10-01/1/advertisers/2/advertiser_campaigns/3.json HTTP/1.1" 404 177 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X)"'

# <IP> <Timestamp> <Request Method> <Request Path> <Request format> <Request Protocol> <Response Code> <Response Time ms> <Referrer> <Requesting Client>
request_regex = /(?<ip_address>(\d{1,3}\.){3}\d{1,3}).*\[(?<timestamp>.*)\].*(?<request_method>(GET|POST|PUT|DELETE))\s*(?<request_path>[^.]*)\.(?<request_format>\w+).*(?<response_code>\d{3}).*(?<response_time_ms>\d+)\s*"(?<referrer>[^"]*)"\s"(?<requesting_client>[^"]*)"/
path_regex = /\/api\/(?<api_version>[^\/]*)\/(?<network_id>\d+)\/advertisers\/(?<advertiser_id>\d+)\/advertiser_campaigns\/(?<advertiser_campaign_id>\d+)/
consumer.consume(group_id: 'centralized_log_consumer', topic_id: 'centralized_logs') do |message|
  match = message.value.match(request_regex)
  path_match = match["request_path"].match(path_regex)

  esclient.create(index: "logstash-central_logging",
                  type: "type1",
                  id: message.offset,
                  body: { timestamp: match["timestamp"],
                          log_level: "INFO",
                          ip_address: match["ip_address"],
                          source: "front-end-1",
                          request_method: match["request_method"],
                          request_path: match["request_path"],
                          network_id: path_match["network_id"].to_i,
                          advertiser_id: path_match["advertiser_id"].to_i,
                          advertiser_campaign_id: path_match["advertiser_campaign_id"].to_i,
                          api_version: path_match["api_version"],
                          request_format: match["request_format"],
                          response_code: match["response_code"].to_i,
                          response_time_ms: match["response_time_ms"].to_i,
                          referrer: match["referrer"],
                          requesting_client: match["requesting_client"] })
end
